SELECT AS_OF_DATE, 
  CASE WHEN REGEXP_LIKE(TO_VARCHAR(AS_OF_DATE), '^[0-9]{8}$') AND TRY_TO_DATE(TO_VARCHAR(AS_OF_DATE), 'YYYYMMDD') IS NOT NULL 
       THEN 'In YYYYMMDD' ELSE 'Not in YYYYMMDD' END AS ASOFDATE_VALID,
  CASE WHEN EXCEPTION_INDICATOR = 'N' THEN 'Pass' ELSE 'Fail' END AS INDICATOR,
  CASE WHEN REGEXP_LIKE(TRANSACTION_AMOUNT, '^-?[0-9]+\\.[0-9]{2}$') THEN 'Pass' ELSE 'Fail' END AS TWO_DECIMAL
FROM ENT_FIN_DEV_PL_DB.ACCOUNTING_HUB.INVSTMNT_AFCS_EXTRACT
WHERE DATA_SOURCE_CODE_DESCRIPTION='Investran Source';